---
- name: 'Post-installation tasks for Containerd'
  become: true
  block:
    - name: 'Ensure Containerd is running and enabled at boot'
      ansible.builtin.systemd:
        name: 'containerd'
        state: 'started'
        enabled: true
      when: not ansible_check_mode
