---
- name: 'Debian | Configure the repository and install the Containerd package'
  become: true
  block:
    - name: 'Debian | Ensure the dependencies are installed'
      ansible.builtin.apt:
        name:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'gnupg'
        update_cache: true
        state: 'present'
      check_mode: false

    - name: 'Debian | Add the Containerd repository GPG key'
      ansible.builtin.apt_key:
        url: '{{ _containerd_repository_gpgkey_url }}'
        keyring: '{{ _containerd_repository_gpgkey_keyring }}'
        state: 'present'

    - name: 'Debian | Add the Containerd repository'
      ansible.builtin.template:
        src: 'docker.list.j2'
        dest: '/etc/apt/sources.list.d/docker.list'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Debian | Install the Containerd package'
      ansible.builtin.apt:
        name: "containerd.io{{ ('=' + containerd_package_version) if (containerd_package_version | length) else '' }}"
        allow_downgrade: true
        update_cache: true
        state: "{{ 'present' if (containerd_package_version | length) else 'latest' }}"
      ignore_errors: '{{ ansible_check_mode }}'
