---
- name: 'Configure APT repository and install Containerd package'
  become: true
  block:
    - name: 'Ensure dependencies are installed'
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
        update_cache: true
        state: present

    - name: 'Add Containerd APT key'
      ansible.builtin.apt_key:
        url: '{{ _containerd_apt_repository_gpgkey }}'
        keyring: '{{ _containerd_apt_local_gpgkey }}'
        state: present
      when: not ansible_check_mode

    - name: 'Add Containerd APT repository'
      ansible.builtin.template:
        src: 'docker.list.j2'
        dest: '/etc/apt/sources.list.d/docker.list'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Install Containerd package'
      ansible.builtin.apt:
        name: "containerd.io{{ ('=' + containerd_version) if (containerd_version | length) else '' }}"
        allow_downgrade: "{{ omit if ansible_version['full'] is version('2.12', '<') else true }}"
        update_cache: true
        state: "{{ 'present' if (containerd_version | length) else 'latest' }}"
