---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that Containerd service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['containerd.service'].state == 'running' or
            ansible_facts.services['containerd.service'].state == 'active'
          - ansible_facts.services['containerd.service'].status == 'enabled'

    - name: 'Check the current Containerd version'
      ansible.builtin.command:
        cmd: '/usr/bin/containerd --version'
      changed_when: false
      register: __containerd_version_check

    - name: 'The Containerd version output'
      ansible.builtin.debug:
        msg: 'The current Containerd version is {{ __containerd_version_check.stdout_lines[0].split()[2] }}'

    - name: 'Pull hello-world image'
      ansible.builtin.command:
        cmd: '/usr/bin/ctr image pull docker.io/library/hello-world:latest'
      changed_when: false

    - name: 'Run hello-world container'
      ansible.builtin.command:
        cmd: '/usr/bin/ctr run --rm docker.io/library/hello-world:latest hello-world'
      changed_when: false
      register: __hello_world

    - name: 'Hello world output'
      ansible.builtin.debug:
        var: __hello_world.stdout_lines
