# ctr image pull docker.io/library/hello-world:latest
# ctr run --rm docker.io/library/hello-world:latest hello-world
---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Gathering Service Facts'
      ansible.builtin.service_facts:

    - name: 'Assert that Containerd service is enabled and running'
      ansible.builtin.assert:
        that:
          - ansible_facts.services['containerd.service'].state == 'running' or
            ansible_facts.services['containerd.service'].state == 'active'
          - ansible_facts.services['containerd.service'].status == 'enabled' or
            ansible_facts.services['containerd.service'].status == 'enabled'

    - name: 'Check current Containerd version'
      ansible.builtin.command:
        cmd: '/usr/bin/containerd --version'
      changed_when: false
      register: _containerd_version_check

    - name: 'Version output'
      ansible.builtin.debug:
        var: _containerd_version_check.stdout_lines[0]

    - name: 'Pull hello-world image'
      shell: ctr image pull docker.io/library/hello-world:latest
      changed_when: false

    - name: 'Run hello-world container'
      shell: ctr run --rm docker.io/library/hello-world:latest hello-world
      changed_when: false
      register: _hello_world

    - name: 'Hello world output'
      ansible.builtin.debug:
        var: _hello_world.stdout_lines
